force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>BK-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Propierty__c.field-meta.xml
<CustomField>
    <fullName>Propierty__c</fullName>
    <label>Propierty</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Travelers__c.field-meta.xml
<CustomField>
    <fullName>Travelers__c</fullName>
    <label>Travelers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/User_AirBnb__c.field-meta.xml
<CustomField>
    <fullName>User_AirBnb__c</fullName>
    <label>User_AirBnb</label>
    <referenceTo>User_AirBnb__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Possible_Dates__c/Possible_Dates__c.object-meta.xml
<CustomObject>
    <label>Possible Dates</label>
    <nameField>
        <displayFormat>PD-{0000}</displayFormat>
        <label>Possible Dates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Possibles Dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Possible_Dates__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Possibles Dates</relationshipLabel>
    <relationshipName>Possibles_Dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Possible_Dates__c.field-meta.xml
<CustomField>
    <fullName>Possible_Dates__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Possible Dates</label>
    <referenceTo>Possible_Dates__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Price_x_night__c.field-meta.xml
<CustomField>
    <fullName>Price_x_night__c</fullName>
    <label>Price x night</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Total_Bathrooms__c.field-meta.xml
<CustomField>
    <fullName>Total_Bathrooms__c</fullName>
    <label>Total Bathrooms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Total_Ocu__c.field-meta.xml
<CustomField>
    <fullName>Total_Ocu__c</fullName>
    <label>Total Occupancy</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/User_AirBnb__c.field-meta.xml
<CustomField>
    <fullName>User_AirBnb__c</fullName>
    <label>User_AirBnb</label>
    <referenceTo>User_AirBnb__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>RVW-{0000}</displayFormat>
        <label>Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Propierty__c.field-meta.xml
<CustomField>
    <fullName>Propierty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Propierty</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_AirBnb__c/User_AirBnb__c.object-meta.xml
<CustomObject>
    <label>User_AirBnb</label>
    <nameField>
        <label>User_AirBnb Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users AirBnb</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_AirBnb__c/fields/isOwner__c.field-meta.xml
<CustomField>
    <fullName>isOwner__c</fullName>
    <label>isOwner</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Is Owner</fullName>
            </value>
            <value>
                <fullName>Not Owner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateDataByFlow.cls
public with sharing class CreateDataByFlow {
    @InvocableMethod(label = 'Create Example Data' description = 'Insert Example Records')
    public static void run(){
        List<User_AirBnb__c> UserAirBnbList = new List<User_AirBnb__c>();
    UserAirBnbList.add(
      new User_AirBnb__c(
        Name = 'Thiago',
        Last_Name__c = 'Schmitz',
        Phone__c = '2583539234',
        isOwner__c = 'Not Owner',
        Adress__latitude__s = -38.942282,
        Adress__longitude__s = -68.103731
      )
    );
    UserAirBnbList.add(
      new User_AirBnb__c(
        Name = 'Agustin',
        Last_Name__c = 'Pfeiffer',
        Phone__c = '3452342422',
        isOwner__c = 'Is Owner',
        Adress__latitude__s = -31.384724,
        Adress__longitude__s = -64.201224
      )
    );
    UserAirBnbList.add(
      new User_AirBnb__c(
        Name = 'Jose M.',
        Last_Name__c = 'Cuenca',
        Phone__c = '6436346346',
        isOwner__c = 'Not Owner',
        Adress__latitude__s = -34.587570,
        Adress__longitude__s = -60.967293
      )
    );
    UserAirBnbList.add(
      new User_AirBnb__c(
        Name = 'Nico',
        Last_Name__c = 'Linares',
        Phone__c = '3452345345',
        isOwner__c = 'Not Owner',
        Adress__latitude__s = -38.715680,
        Adress__longitude__s = -62.283246
      )
    );
    UserAirBnbList.add(
      new User_AirBnb__c(
        Name = 'Ciro',
        Last_Name__c = 'Bogari',
        Phone__c = '6546434555',
        isOwner__c = 'Is Owner',
        Adress__latitude__s = -40.985190,
        Adress__longitude__s = -70.724369
      )
    );

    insert UserAirBnbList;

    // Create 2 Possibles dates to rental a property
    List<Possible_Dates__c> PossibleDatesList = new List<Possible_Dates__c>();
    // 6 noches en Florianópolis
    PossibleDatesList.add(
      new Possible_Dates__c(
        Start_Date__c = date.parse('08/01/2022'),
        End_Date__c = date.parse('08/25/2022')
      )
    );
    PossibleDatesList.add(
      new Possible_Dates__c(
        Start_Date__c = date.parse('09/05/2022'),
        End_Date__c = date.parse('09/30/2022')
      )
    );

    insert PossibleDatesList;

    // I create 2 Playlist for each Listener ---> Total 6PL
    List<Property__c> propertyList = new List<Property__c>();
    // 6 noches en Florianópolis
    propertyList.add(
      new Property__c(
        Name = 'Cabaña de Montaña- Al lado del Rio- Sierras',
        Adress__latitude__s = -31.617275,
        Adress__longitude__s = -65.070828,
        Description__c = 'Un espacio único para descansar y desconectarse.',
        Price_x_night__c = 3500,
        User_AirBnb__c = UserAirBnbList[1].id,
        Total_Bathrooms__c = 2,
        Total_Ocu__c = 4,
        Total_Rooms__c = 2
      )
    );

    propertyList.add(
      new Property__c(
        Name = 'BAM | DEPTO LAS VICTORIAS',
        Adress__latitude__s = -41.191542,
        Adress__longitude__s = -71.178931,
        Description__c = 'Departamento en complejo residencial entero. Relájate con toda la familia en este alojamiento donde la tranquilidad se respira.',
        Price_x_night__c = 6800,
        User_AirBnb__c = UserAirBnbList[4].id,
        Total_Bathrooms__c = 3,
        Total_Ocu__c = 8,
        Total_Rooms__c = 4
      )
    );

    insert propertyList;

    List<Booking__c> BookingList = new List<Booking__c>();
    // 6 noches en Florianópolis
    BookingList.add(
      new Booking__c(
        Propierty__c = propertyList[0].id,
        User_AirBnb__c = UserAirBnbList[0].id,
        Start_Date__c = date.parse('08/10/2022'),
        End_Date__c = date.parse('08/23/2022'),
        Travelers__c = 3
      )
    );
    BookingList.add(
      new Booking__c(
        Propierty__c = propertyList[1].id,
        User_AirBnb__c = UserAirBnbList[3].id,
        Start_Date__c = date.parse('09/05/2022'),
        End_Date__c = date.parse('09/21/2022'),
        Travelers__c = 3
      )
    );
    insert BookingList;

    List<Review__c> ReviewList = new List<Review__c>();
    // 6 noches en Florianópolis
    ReviewList.add(
      new Review__c(
        Booking__c = BookingList[0].id,
        Propierty__c = BookingList[0].Propierty__c,
        Description__c = 'La casa tiene un encanto natural , Se disfruta en el exterior como interior. Tiene todo lo necesario para una estadía de desconexión. Un parque hermoso y una orientación ideal para el sol en pleno bosque.',
        Points__c = 8
      )
    );

    insert ReviewList;
    }
}