force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>BK-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Propierty__c.field-meta.xml
<CustomField>
    <fullName>Propierty__c</fullName>
    <label>Propierty</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/User_AirBnb__c.field-meta.xml
<CustomField>
    <fullName>User_AirBnb__c</fullName>
    <label>User_AirBnb</label>
    <referenceTo>User_AirBnb__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Possible_Dates__c/Possible_Dates__c.object-meta.xml
<CustomObject>
    <label>Possible Dates</label>
    <nameField>
        <displayFormat>PD-{0000}</displayFormat>
        <label>Possible Dates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Possibles Dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Possible_Dates__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Possibles Dates</relationshipLabel>
    <relationshipName>Possibles_Dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Possible_Dates__c.field-meta.xml
<CustomField>
    <fullName>Possible_Dates__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Possible Dates</label>
    <referenceTo>Possible_Dates__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/User_AirBnb__c.field-meta.xml
<CustomField>
    <fullName>User_AirBnb__c</fullName>
    <label>User_AirBnb</label>
    <referenceTo>User_AirBnb__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>RVW-{0000}</displayFormat>
        <label>Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Propierty__c.field-meta.xml
<CustomField>
    <fullName>Propierty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Propierty</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_AirBnb__c/User_AirBnb__c.object-meta.xml
<CustomObject>
    <label>User_AirBnb</label>
    <nameField>
        <label>User_AirBnb Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users AirBnb</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BookingTriggerTest.cls
@IsTest
public with sharing class BookingTriggerTest {

    @isTest static void testSuccessInsertBooking(){
        CreateDataByFlow.run();
        List<Property__c> propertyList = [SELECT id FROM Property__C];
        List<User_AirBnb__c> UserAirBnbList = [SELECT id FROM User_AirBnb__c];

        Test.startTest();
        insert new Booking__c(Propierty__c = propertyList[0].Id, User_AirBnb__c = UserAirBnbList[0].Id);
        List<Booking__c> bookingList = [SELECT Id FROM Booking__C];
        System.assertEquals(3, bookingList.size());
        Test.stopTest();
    }

    @isTest static void testFailInsertBooking(){
        CreateDataByFlow.run();
        List<Property__c> propertyList = [SELECT id FROM Property__C];
        List<User_AirBnb__c> UserAirBnbList = [SELECT id FROM User_AirBnb__c];
        List<Booking__c> bookingList = new List<Booking__c>();
        bookingList.add(new Booking__c(Propierty__c = propertyList[0].Id, User_AirBnb__c = UserAirBnbList[1].Id));

        Test.startTest();
        Database.SaveResult[] bookingInserResult = Database.insert(bookingList, false);
        Test.stopTest();

        Integer succesfull = 0;
        Integer failed = 0;

        for(Database.SaveResult result :bookingInserResult){
            if(result.isSuccess()){
                succesfull++;
            }else{
                failed++;
            }
        }
        System.assertEquals(1, failed);
    }
    
    
    @isTest static void testCreateDataByFlow (){
    CreateDataByFlow.run();
    List<User_AirBnb__c> UserAirBnbList = [SELECT id, name FROM User_AirBnb__c];
    List<Possible_Dates__c> PossibleDatesList = [SELECT id, name FROM Possible_Dates__c];
    List<Property__c> propertyList = [SELECT id, name FROM Property__c]; 
    List<Booking__c> BookingList = [SELECT id, name FROM Booking__c];
    List<Review__c> ReviewList = [SELECT id, name FROM Review__c];


    System.assertEquals(5,UserAirBnbList.size());
    System.assertEquals(2,PossibleDatesList.size());
    System.assertEquals(2,propertyList.size());
    System.assertEquals(2,BookingList.size());
    System.assertEquals(1,ReviewList.size());
  }
}